
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 82104
 */
public class AutomaticFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String strSQL = "";
    
    
    
    /**
     * Creates new form AutomaticFrame
     */
    public AutomaticFrame() {
        initComponents();
        lblSubTitle.setVisible(false);
        
        String user_money = "";
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNum = new javax.swing.JLabel();
        lblRealMyNum = new javax.swing.JLabel();
        lblMyNum = new javax.swing.JLabel();
        lblRealNum = new javax.swing.JLabel();
        lblCheck = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        btnMy = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnClick = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("자동");

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("*자동 로또");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblNum.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblNum.setForeground(new java.awt.Color(0, 0, 255));
        lblNum.setText("당첨 번호 : ");

        lblRealMyNum.setFont(new java.awt.Font("맑은 고딕", 3, 14)); // NOI18N
        lblRealMyNum.setText("자동");

        lblMyNum.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblMyNum.setText("내 번호 : ");

        lblRealNum.setFont(new java.awt.Font("맑은 고딕", 3, 18)); // NOI18N
        lblRealNum.setForeground(new java.awt.Color(0, 0, 255));
        lblRealNum.setText("당첨");

        lblCheck.setText("몇개 번호 일치?");

        lblSubTitle.setFont(new java.awt.Font("맑은 고딕", 3, 14)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(153, 0, 153));
        lblSubTitle.setText("<< 몇번 회차 즉석 복권 >>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMyNum)
                                .addGap(18, 18, 18)
                                .addComponent(lblRealMyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNum)
                                .addGap(18, 18, 18)
                                .addComponent(lblRealNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSubTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(lblRealNum))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyNum)
                    .addComponent(lblRealMyNum))
                .addGap(43, 43, 43)
                .addComponent(lblCheck)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnMy.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnMy.setText("마이페이지");
        btnMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnClick.setBackground(new java.awt.Color(255, 204, 255));
        btnClick.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnClick.setText("자동 복권 참여");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        btnBack.setText(" 🔙");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("잔액 : ");

        lblChange.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btnMy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMy)
                    .addComponent(btnLogout)
                    .addComponent(btnBack)
                    .addComponent(jLabel1)
                    .addComponent(lblChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyActionPerformed
        // TODO add your handling code here:
        MyPageFrame mpf = new MyPageFrame();
        mpf.setVisible(true);
        mpf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnMyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ChoiceFrame sf = new ChoiceFrame();
        sf.setVisible(true);
        sf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        String user_money = "";
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        if(Integer.parseInt(user_money) == 0){
            JOptionPane.showMessageDialog(null, "잔액이 없습니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        strSQL = "Select Round from Lottery where Lottery.ID = '" + UserIDC.user_id + "' "
                + "order by Round";
        String strRound = "";
        int round = 0;
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                strRound = DBM.DB_rs.getString("Round");
            }
            
            
            if(strRound.equals("")){
                round = 1;
            }else{
                round = Integer.parseInt(strRound) + 1;
            }
            
            lblSubTitle.setText("<<" + round + "번 회차 즉석 복권>>");
            lblSubTitle.setVisible(true);
            
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }

        
        int[] showLottoNumber = new int[6];
        int[] showUserNumber = new int[6];
        
        ArrayList lottoNumber = new ArrayList<Integer>();
        ArrayList userNumber = new ArrayList<Integer>();
        for(int i = 1 ; i <= 45 ; i++) {
            lottoNumber.add(i);
            userNumber.add(i);
        }
        Collections.shuffle(lottoNumber);
        Collections.shuffle(userNumber);
        for(int i = 0 ; i < 6 ; i++) {
            showLottoNumber[i] = (int)lottoNumber.get(i);
            showUserNumber[i] = (int)userNumber.get(i);
        }
        
        Arrays.sort(showLottoNumber);
        Arrays.sort(showUserNumber);
        
        String strShowLottery = Arrays.toString(showLottoNumber).replaceAll("[^0-9 ]","");
        String strShowUser = Arrays.toString(showUserNumber).replaceAll("[^0-9 ]","");
        
        lblRealNum.setText(strShowLottery);
        lblRealMyNum.setText(strShowUser);
        
        int checkCount = 0;
        int prize = 0;
        String strCheck = "";
        
        for(int i = 0; i < showLottoNumber.length; i++){
            for(int j = 0; j < showUserNumber.length; j++){
                if(showLottoNumber[i] == showUserNumber[j]){
                    checkCount++;
                }
            }
        }
        
        switch(checkCount){
            case 0:
            case 1:
                strCheck = "낙첨 되셨습니다.";
                break;
            case 2:
                prize = 1000;
                strCheck = "5등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 3:
                prize = 10000;
                strCheck = "4등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 4:
                prize = 100000;
                strCheck = "3등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 5:
                prize = 10000000;
                strCheck = "2등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 6:
                prize = 1000000000;
                strCheck = "1등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
        }
        lblCheck.setText(strCheck);
        
        int money = Integer.parseInt(user_money) + prize - 1000;
        
        strSQL = "Update Users Set Users.Money = '" + money + "' Where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        
        strSQL = "Insert Into Lottery Values (";
        strSQL += "'" + round + "',";
        strSQL += "'" + strShowLottery + "',";
        strSQL += "'AUTO',";
        strSQL += "'" + checkCount + "',";
        strSQL += "'" + prize + "',";
        strSQL += "'" + UserIDC.user_id + "')";
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnClickActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomaticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomaticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomaticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomaticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomaticFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblMyNum;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRealMyNum;
    private javax.swing.JLabel lblRealNum;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
