

import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 82104
 */
public class JoinMemberFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String strSQL = "Select id From Users ";

    /**
     * Creates new form MemberFrame
     */
    public JoinMemberFrame() {
        initComponents();
    }

    int reBtnClick = 1;
    String idText = "";

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnMember = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        lblPasswdCheck = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnDupli = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassCheck = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("회원가입");

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("회원가입");

        btnMember.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnMember.setText("회원가입");
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblID.setText("아이디");

        lblPasswd.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPasswd.setText("비밀번호");

        lblPasswdCheck.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPasswdCheck.setText("비밀번호 확인");

        lblName.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblName.setText("이름");

        btnDupli.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnDupli.setText("중복확인");
        btnDupli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDupliActionPerformed(evt);
            }
        });

        btnBack.setText(" 🔙");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswdCheck)
                            .addComponent(lblPasswd)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassCheck)
                            .addComponent(txtID)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtPass))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMember)
                            .addComponent(btnDupli))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(btnDupli)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswd)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswdCheck)
                    .addComponent(txtPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMember)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "아이디를 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!(idText.equals(txtID.getText())) || reBtnClick != 0){
            JOptionPane.showMessageDialog(null, "아이디 중복확인을 해주세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(txtPass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "패스워드를 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(txtPassCheck.getText().equals("")){
            JOptionPane.showMessageDialog(null, "패스워드 확인란을 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "이름을 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String pwd = txtPass.getText().trim();
        String salt = Utils.getSalt();
        String pwdgetEncrypt = Utils.getEncrypt(pwd, salt);
        
        
        
        if(Arrays.equals(txtPass.getPassword(),txtPassCheck.getPassword())){
            strSQL = "Insert Into Users Values (";
            strSQL += "'" + txtID.getText().trim() + "',";
            strSQL += "'" + pwdgetEncrypt + "',";
            strSQL += "'" + txtName.getText().trim() + "',";
            strSQL += 100000 + ",";
            strSQL += "'" + salt + "')";
            
            try{
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                DBM.dbClose();
            }catch(Exception e){
                System.out.println("SQLException : " + e.getMessage());
            }
            
            reBtnClick = 1;
        }else{
            JOptionPane.showMessageDialog(null, "비밀번호가 맞지 않습니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LoginFrame jf = new LoginFrame();
        jf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnDupliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDupliActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "아이디를 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        strSQL = "Select ID From Users Where Users.ID = '" + txtID.getText().trim() + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            String id = "";
            while(DBM.DB_rs.next()){
                id = DBM.DB_rs.getString("ID");
            }
            if(id != ""){
                JOptionPane.showMessageDialog(null, "이미 사용중인 아이디 입니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                reBtnClick = 1;
                DBM.DB_rs.close();
                DBM.dbClose();
                return;
            }
            JOptionPane.showMessageDialog(null, "사용 가능한 아이디 입니다.", "알림", JOptionPane.INFORMATION_MESSAGE);
            reBtnClick = 0;
            idText = txtID.getText();
            
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnDupliActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        lf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinMemberFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDupli;
    private javax.swing.JButton btnMember;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblPasswdCheck;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassCheck;
    // End of variables declaration//GEN-END:variables
}
