
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 82104
 */
public class ManualFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String strSQL = "";
    
    /**
     * Creates new form ManualFrame
     */
    public ManualFrame() {
        initComponents();
        
        String user_money = "";
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNum = new javax.swing.JLabel();
        lblRealMyNum = new javax.swing.JLabel();
        lblMyNum = new javax.swing.JLabel();
        lblRealNum = new javax.swing.JLabel();
        lblCheck = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        btnMy = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        cbx20 = new javax.swing.JCheckBox();
        cbx16 = new javax.swing.JCheckBox();
        cbx17 = new javax.swing.JCheckBox();
        cbx18 = new javax.swing.JCheckBox();
        cbx19 = new javax.swing.JCheckBox();
        cbx11 = new javax.swing.JCheckBox();
        cbx12 = new javax.swing.JCheckBox();
        cbx13 = new javax.swing.JCheckBox();
        cbx14 = new javax.swing.JCheckBox();
        cbx15 = new javax.swing.JCheckBox();
        cbx30 = new javax.swing.JCheckBox();
        cbx26 = new javax.swing.JCheckBox();
        cbx27 = new javax.swing.JCheckBox();
        cbx28 = new javax.swing.JCheckBox();
        cbx29 = new javax.swing.JCheckBox();
        cbx21 = new javax.swing.JCheckBox();
        cbx22 = new javax.swing.JCheckBox();
        cbx23 = new javax.swing.JCheckBox();
        cbx24 = new javax.swing.JCheckBox();
        cbx25 = new javax.swing.JCheckBox();
        cbx40 = new javax.swing.JCheckBox();
        cbx36 = new javax.swing.JCheckBox();
        cbx37 = new javax.swing.JCheckBox();
        cbx38 = new javax.swing.JCheckBox();
        cbx39 = new javax.swing.JCheckBox();
        cbx31 = new javax.swing.JCheckBox();
        cbx32 = new javax.swing.JCheckBox();
        cbx33 = new javax.swing.JCheckBox();
        cbx34 = new javax.swing.JCheckBox();
        cbx35 = new javax.swing.JCheckBox();
        cbx41 = new javax.swing.JCheckBox();
        cbx42 = new javax.swing.JCheckBox();
        cbx43 = new javax.swing.JCheckBox();
        cbx44 = new javax.swing.JCheckBox();
        cbx45 = new javax.swing.JCheckBox();
        btnClick = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        cbx10 = new javax.swing.JCheckBox();
        cbx6 = new javax.swing.JCheckBox();
        cbx7 = new javax.swing.JCheckBox();
        cbx8 = new javax.swing.JCheckBox();
        cbx9 = new javax.swing.JCheckBox();
        cbx1 = new javax.swing.JCheckBox();
        cbx2 = new javax.swing.JCheckBox();
        cbx3 = new javax.swing.JCheckBox();
        cbx4 = new javax.swing.JCheckBox();
        cbx5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("수동");

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("*수동 로또");

        btnBack.setText(" 🔙");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblNum.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblNum.setForeground(new java.awt.Color(0, 0, 255));
        lblNum.setText("당첨 번호 : ");

        lblRealMyNum.setFont(new java.awt.Font("맑은 고딕", 3, 14)); // NOI18N
        lblRealMyNum.setText("수동");

        lblMyNum.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblMyNum.setText("내 번호 : ");

        lblRealNum.setFont(new java.awt.Font("맑은 고딕", 3, 18)); // NOI18N
        lblRealNum.setForeground(new java.awt.Color(0, 0, 255));
        lblRealNum.setText("당첨");

        lblCheck.setText("몇개 번호 일치?");

        lblSubTitle.setFont(new java.awt.Font("맑은 고딕", 3, 14)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(153, 0, 153));
        lblSubTitle.setText("<< 몇번 회차 즉석 복권 >>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMyNum)
                        .addGap(18, 18, 18)
                        .addComponent(lblRealMyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNum)
                        .addGap(18, 18, 18)
                        .addComponent(lblRealNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSubTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(lblRealNum))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyNum)
                    .addComponent(lblRealMyNum))
                .addGap(43, 43, 43)
                .addComponent(lblCheck)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnMy.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnMy.setText("마이페이지");
        btnMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        cbx20.setText("20");

        cbx16.setText("16");

        cbx17.setText("17");

        cbx18.setText("18");

        cbx19.setText("19");

        cbx11.setText("11");

        cbx12.setText("12");

        cbx13.setText("13");

        cbx14.setText("14");

        cbx15.setText("15");

        cbx30.setText("30");

        cbx26.setText("26");

        cbx27.setText("27");

        cbx28.setText("28");

        cbx29.setText("29");

        cbx21.setText("21");

        cbx22.setText("22");

        cbx23.setText("23");

        cbx24.setText("24");

        cbx25.setText("25");

        cbx40.setText("40");

        cbx36.setText("36");

        cbx37.setText("37");

        cbx38.setText("38");

        cbx39.setText("39");

        cbx31.setText("31");

        cbx32.setText("32");

        cbx33.setText("33");

        cbx34.setText("34");

        cbx35.setText("35");

        cbx41.setText("41");

        cbx42.setText("42");

        cbx43.setText("43");

        cbx44.setText("44");

        cbx45.setText("45");

        btnClick.setBackground(new java.awt.Color(255, 204, 255));
        btnClick.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnClick.setText("수동 복권 참여");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        jLabel1.setText("잔액 : ");

        lblChange.setText("jLabel2");

        cbx10.setText("10");

        cbx6.setText("06");

        cbx7.setText("07");

        cbx8.setText("08");

        cbx9.setText("09");

        cbx1.setText("01");

        cbx2.setText("02");

        cbx3.setText("03");

        cbx4.setText("04");

        cbx5.setText("05");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblTitle)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnMy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbx21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbx31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx40)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbx41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx45)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbx1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMy)
                            .addComponent(btnLogout)
                            .addComponent(btnBack))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblChange))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx1)
                    .addComponent(cbx2)
                    .addComponent(cbx3)
                    .addComponent(cbx4)
                    .addComponent(cbx5)
                    .addComponent(cbx6)
                    .addComponent(cbx7)
                    .addComponent(cbx8)
                    .addComponent(cbx9)
                    .addComponent(cbx10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx11)
                    .addComponent(cbx12)
                    .addComponent(cbx13)
                    .addComponent(cbx14)
                    .addComponent(cbx15)
                    .addComponent(cbx16)
                    .addComponent(cbx17)
                    .addComponent(cbx18)
                    .addComponent(cbx19)
                    .addComponent(cbx20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx21)
                    .addComponent(cbx22)
                    .addComponent(cbx23)
                    .addComponent(cbx24)
                    .addComponent(cbx25)
                    .addComponent(cbx26)
                    .addComponent(cbx27)
                    .addComponent(cbx28)
                    .addComponent(cbx29)
                    .addComponent(cbx30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx31)
                    .addComponent(cbx32)
                    .addComponent(cbx33)
                    .addComponent(cbx34)
                    .addComponent(cbx35)
                    .addComponent(cbx36)
                    .addComponent(cbx37)
                    .addComponent(cbx38)
                    .addComponent(cbx39)
                    .addComponent(cbx40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx41)
                    .addComponent(cbx42)
                    .addComponent(cbx43)
                    .addComponent(cbx44)
                    .addComponent(cbx45))
                .addGap(18, 18, 18)
                .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyActionPerformed
        // TODO add your handling code here:
        MyPageFrame mpf = new MyPageFrame();
        mpf.setVisible(true);
        mpf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnMyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ChoiceFrame sf = new ChoiceFrame();
        sf.setVisible(true);
        sf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        String user_money = "";
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        if(Integer.parseInt(user_money) == 0){
            JOptionPane.showMessageDialog(null, "잔액이 없습니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        strSQL = "Select Round from Lottery where Lottery.ID = '" + UserIDC.user_id + "'" + "order by Round";
        String strRound = "";
        int round = 0;
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                strRound = DBM.DB_rs.getString("Round");
            }
            
            if(strRound.equals("")){
                round = 1;
            }else{
                round = Integer.parseInt(strRound) + 1;
            }
            
            lblSubTitle.setText("<<" + round + "번 회차 즉석 복권>>");
            lblSubTitle.setVisible(true);
            
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }

        
        int[] showLottoNumber = new int[6];
        ArrayList<Integer> showUserNumbers = new ArrayList();
        int numCount = 0;

        if(cbx1.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx1.getText()));
            numCount++;
        }
        if(cbx2.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx2.getText()));
            numCount++;
        }
        if(cbx3.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx3.getText()));
            numCount++;
        }
        if(cbx4.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx4.getText()));
            numCount++;
        }
        if(cbx5.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx5.getText()));
            numCount++;
        }
        if(cbx6.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx6.getText()));
            numCount++;
        }
        if(cbx7.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx7.getText()));
            numCount++;
        }
        if(cbx8.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx8.getText()));
            numCount++;
        }
        if(cbx9.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx9.getText()));
            numCount++;
        }
        if(cbx10.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx10.getText()));
            numCount++;
        }
        if(cbx11.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx11.getText()));
            numCount++;
        }
        if(cbx12.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx12.getText()));
            numCount++;
        }
        if(cbx13.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx13.getText()));
            numCount++;
        }
        if(cbx14.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx14.getText()));
            numCount++;
        }
        if(cbx15.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx15.getText()));
            numCount++;
        }
        if(cbx16.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx16.getText()));
            numCount++;
        }
        if(cbx17.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx17.getText()));
            numCount++;
        }
        if(cbx18.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx18.getText()));
            numCount++;
        }
        if(cbx19.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx19.getText()));
            numCount++;
        }
        if(cbx20.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx20.getText()));
            numCount++;
        }
        if(cbx21.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx21.getText()));
            numCount++;
        }
        if(cbx22.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx22.getText()));
            numCount++;
        }
        if(cbx23.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx23.getText()));
            numCount++;
        }
        if(cbx24.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx24.getText()));
            numCount++;
        }
        if(cbx25.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx25.getText()));
            numCount++;
        }
        if(cbx26.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx26.getText()));
            numCount++;
        }
        if(cbx27.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx27.getText()));
            numCount++;
        }
        if(cbx28.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx28.getText()));
            numCount++;
        }
        if(cbx29.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx29.getText()));
            numCount++;
        }
        if(cbx30.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx30.getText()));
            numCount++;
        }
        if(cbx31.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx31.getText()));
            numCount++;
        }
        if(cbx32.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx32.getText()));
            numCount++;
        }
        if(cbx33.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx33.getText()));
            numCount++;
        }
        if(cbx34.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx34.getText()));
            numCount++;
        }
        if(cbx35.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx35.getText()));
            numCount++;
        }
        if(cbx36.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx36.getText()));
            numCount++;
        }
        if(cbx37.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx37.getText()));
            numCount++;
        }
        if(cbx38.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx38.getText()));
            numCount++;
        }
        if(cbx39.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx39.getText()));
            numCount++;
        }
        if(cbx40.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx40.getText()));
            numCount++;
        }
        if(cbx41.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx41.getText()));
            numCount++;
        }
        if(cbx42.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx42.getText()));
            numCount++;
        }
        if(cbx43.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx43.getText()));
            numCount++;
        }
        if(cbx44.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx44.getText()));
            numCount++;
        }
        if(cbx45.isSelected()){
            showUserNumbers.add(Integer.parseInt(cbx45.getText()));
            numCount++;
        }
        
        if(numCount < 6){
            JOptionPane.showMessageDialog(null, "번호를 6개 선택 해주세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(showUserNumbers.size() > 6){
            JOptionPane.showMessageDialog(null, "번호를 6개만 선택 해주세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int[] showUserNumber = showUserNumbers.stream().mapToInt(Integer::intValue).toArray();
        
        
        ArrayList lottoNumber = new ArrayList<Integer>();
        for(int i = 1 ; i <= 45 ; i++) {
            lottoNumber.add(i);
        }
        Collections.shuffle(lottoNumber);
        
        for(int i = 0 ; i < 6 ; i++) {
            showLottoNumber[i] = (int)lottoNumber.get(i);
        }
        
        Arrays.sort(showLottoNumber);
        Arrays.sort(showUserNumber);
        
        String strShowLottery = Arrays.toString(showLottoNumber).replaceAll("[^0-9 ]","");
        String strShowUser = Arrays.toString(showUserNumber).replaceAll("[^0-9 ]","");
        
        lblRealNum.setText(strShowLottery);
        lblRealMyNum.setText(strShowUser);
        
        int checkCount = 0;
        int prize = 0;
        String strCheck = "";
        
        for(int i = 0; i < showLottoNumber.length; i++){
            for(int j = 0; j < showUserNumber.length; j++){
                if(showLottoNumber[i] == showUserNumber[j]){
                    checkCount++;
                }
            }
        }
        
        switch(checkCount){
            case 0:
            case 1:
                strCheck = "낙첨 되셨습니다.";
                break;
            case 2:
                prize = 1000;
                strCheck = "5등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 3:
                prize = 10000;
                strCheck = "4등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 4:
                prize = 100000;
                strCheck = "3등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 5:
                prize = 10000000;
                strCheck = "2등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
            case 6:
                prize = 1000000000;
                strCheck = "1등 당첨! " + checkCount + "개 일치합니다. " + prize +  "원 적립";
                break;
        }
        lblCheck.setText(strCheck);
        
        
        int money = Integer.parseInt(user_money) + prize - 1000;
        
        strSQL = "Update Users Set Users.Money = '" + money + "' Where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblChange.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        
        strSQL = "Insert Into Lottery Values (";
        strSQL += "'" + round + "',";
        strSQL += "'" + strShowLottery + "',";
        strSQL += "'Manual',";
        strSQL += "'" + checkCount + "',";
        strSQL += "'" + prize + "',";
        strSQL += "'" + UserIDC.user_id + "')";
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        cbx1.setSelected(false);
        cbx2.setSelected(false);
        cbx3.setSelected(false);
        cbx4.setSelected(false);
        cbx5.setSelected(false);
        cbx6.setSelected(false);
        cbx7.setSelected(false);
        cbx8.setSelected(false);
        cbx9.setSelected(false);
        cbx10.setSelected(false);
        cbx11.setSelected(false);
        cbx12.setSelected(false);
        cbx13.setSelected(false);
        cbx14.setSelected(false);
        cbx15.setSelected(false);
        cbx16.setSelected(false);
        cbx17.setSelected(false);
        cbx18.setSelected(false);
        cbx19.setSelected(false);
        cbx20.setSelected(false);
        cbx21.setSelected(false);
        cbx22.setSelected(false);
        cbx23.setSelected(false);
        cbx24.setSelected(false);
        cbx25.setSelected(false);
        cbx26.setSelected(false);
        cbx27.setSelected(false);
        cbx28.setSelected(false);
        cbx29.setSelected(false);
        cbx30.setSelected(false);
        cbx31.setSelected(false);
        cbx32.setSelected(false);
        cbx33.setSelected(false);
        cbx34.setSelected(false);
        cbx35.setSelected(false);
        cbx36.setSelected(false);
        cbx37.setSelected(false);
        cbx38.setSelected(false);
        cbx39.setSelected(false);
        cbx40.setSelected(false);
        cbx41.setSelected(false);
        cbx42.setSelected(false);
        cbx43.setSelected(false);
        cbx44.setSelected(false);
        cbx45.setSelected(false);
    }//GEN-LAST:event_btnClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMy;
    private javax.swing.JCheckBox cbx1;
    private javax.swing.JCheckBox cbx10;
    private javax.swing.JCheckBox cbx11;
    private javax.swing.JCheckBox cbx12;
    private javax.swing.JCheckBox cbx13;
    private javax.swing.JCheckBox cbx14;
    private javax.swing.JCheckBox cbx15;
    private javax.swing.JCheckBox cbx16;
    private javax.swing.JCheckBox cbx17;
    private javax.swing.JCheckBox cbx18;
    private javax.swing.JCheckBox cbx19;
    private javax.swing.JCheckBox cbx2;
    private javax.swing.JCheckBox cbx20;
    private javax.swing.JCheckBox cbx21;
    private javax.swing.JCheckBox cbx22;
    private javax.swing.JCheckBox cbx23;
    private javax.swing.JCheckBox cbx24;
    private javax.swing.JCheckBox cbx25;
    private javax.swing.JCheckBox cbx26;
    private javax.swing.JCheckBox cbx27;
    private javax.swing.JCheckBox cbx28;
    private javax.swing.JCheckBox cbx29;
    private javax.swing.JCheckBox cbx3;
    private javax.swing.JCheckBox cbx30;
    private javax.swing.JCheckBox cbx31;
    private javax.swing.JCheckBox cbx32;
    private javax.swing.JCheckBox cbx33;
    private javax.swing.JCheckBox cbx34;
    private javax.swing.JCheckBox cbx35;
    private javax.swing.JCheckBox cbx36;
    private javax.swing.JCheckBox cbx37;
    private javax.swing.JCheckBox cbx38;
    private javax.swing.JCheckBox cbx39;
    private javax.swing.JCheckBox cbx4;
    private javax.swing.JCheckBox cbx40;
    private javax.swing.JCheckBox cbx41;
    private javax.swing.JCheckBox cbx42;
    private javax.swing.JCheckBox cbx43;
    private javax.swing.JCheckBox cbx44;
    private javax.swing.JCheckBox cbx45;
    private javax.swing.JCheckBox cbx5;
    private javax.swing.JCheckBox cbx6;
    private javax.swing.JCheckBox cbx7;
    private javax.swing.JCheckBox cbx8;
    private javax.swing.JCheckBox cbx9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblMyNum;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRealMyNum;
    private javax.swing.JLabel lblRealNum;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
