
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 82104
 */
public class MyPageFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String strSQL = "";
    String user_money = "";
    
    /**
     * Creates new form MyPageFrame
     */
    public MyPageFrame() {
        initComponents();
        lblIDName.setText(UserIDC.user_id);
        
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblPointPrice.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        lottoTable();
//        txtCharging.setDocument(new JTextFieldLimit(7));
    }
    
    protected void lottoTable(){
        int idxRow = 0;
        strSQL = "Select TOP 15 * "
                + "From Lottery where Lottery.ID = '" + UserIDC.user_id + "' "
                + "order by Round desc";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                jTable1.setValueAt(DBM.DB_rs.getString("Round"), idxRow, 0);
                jTable1.setValueAt(DBM.DB_rs.getString("Numbers"), idxRow, 1);
                jTable1.setValueAt(DBM.DB_rs.getString("LType"), idxRow, 2);
                jTable1.setValueAt(DBM.DB_rs.getString("Matched"), idxRow, 3);
                jTable1.setValueAt(DBM.DB_rs.getString("Prize"), idxRow, 4);
                idxRow++;
            }
            
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    
    
    
//    public class JTextFieldLimit extends PlainDocument{
//        private int limit;
//        public JTextFieldLimit(int limit){
//            super();
//            this.limit = limit;
//        }
//        
//        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException{
//            if(str == null){
//                return;
//            }
//            
//            if(getLength() + str.length() <= limit){
//                super.insertString(offset, str, attr);
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnOut = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPoint = new javax.swing.JLabel();
        lblPointPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        lblIDName = new javax.swing.JLabel();
        btnCharging = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("마이페이지");

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 102));
        lblTitle.setText("마이페이지");

        btnOut.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnOut.setForeground(new java.awt.Color(255, 51, 51));
        btnOut.setText("회원 탈퇴");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBack.setText(" 🔙");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPoint.setFont(new java.awt.Font("맑은 고딕", 2, 12)); // NOI18N
        lblPoint.setText("잔액 : ");

        lblPointPrice.setFont(new java.awt.Font("맑은 고딕", 2, 12)); // NOI18N
        lblPointPrice.setText("포인트");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "회차", "당첨번호", "복권유형", "일치", "당첨금액"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblID.setText("ID : ");

        lblIDName.setText("id");

        btnCharging.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnCharging.setForeground(new java.awt.Color(0, 0, 255));
        btnCharging.setText("금액 충전");
        btnCharging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargingActionPerformed(evt);
            }
        });

        jLabel2.setText("ex) 충전 시 10만원이 충전됩니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIDName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPoint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPointPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCharging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblIDName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoint)
                    .addComponent(lblPointPrice))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharging, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOut)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ChoiceFrame sf = new ChoiceFrame();
        sf.setVisible(true);
        sf.setLocation(300, 300);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        int checkResult = JOptionPane.showConfirmDialog(null, "회원 탈퇴 하시겠습니까?", "알림", JOptionPane.ERROR_MESSAGE);
        
        if(checkResult == 0){
            strSQL = "Delete From Users where Users.ID = '" + UserIDC.user_id + "' ";

            try{
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                DBM.dbClose();
            }catch(Exception e){
                System.out.println("SQLException : " + e.getMessage());
            }

            strSQL = "Delete From Lottery where Lottery.ID = '" + UserIDC.user_id + "' ";

            try{
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                DBM.dbClose();
            }catch(Exception e){
                System.out.println("SQLException : " + e.getMessage());
            }
            
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnChargingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargingActionPerformed
        // TODO add your handling code here:
        int money = 0;
        strSQL = "Select Money From Users Where Users.ID = '" + UserIDC.user_id + "'";
        
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
//            money = Integer.parseInt(user_money) + Integer.parseInt(txtCharging.getText());

            money = Integer.parseInt(user_money);
            DBM.dbClose();
            
            if(money != 0){
                JOptionPane.showMessageDialog(null, "잔액이 없으면 충전됩니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        
        strSQL = "Update Users Set Users.Money = '" + 100000 + "' Where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        
        strSQL = "Select Money From Users where Users.ID = '" + UserIDC.user_id + "'";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                user_money = DBM.DB_rs.getString("Money");
            }
            
            lblPointPrice.setText(user_money);
            DBM.DB_rs.close();
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
//        txtCharging.setText("");
    }//GEN-LAST:event_btnChargingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCharging;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDName;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JLabel lblPointPrice;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
